### ISSUE TITLE
Preview another file formats

### ISSUE THREAD

**Issue by lubien** [projeto-spider/spider-gap-analysis#19]
Currently I only preview images.

- [X] PDF (#23)
- [x] Video (#24)
- [X] Audio (#27)

https://github.com/projeto-spider/spider-gap-analysis/blob/master/resources/components/evidence-modal.vue#L4-L8

**Comment by lubien** [comment]
**Might** be possible to preview PDF with an iframe, but I'm unsure.

**Comment by urielfcampos** [comment]
I also believe it's possible to preview pdf with an iframe from what I've read.
and video preview should be possible with html5 and some simple javascript.

**Comment by lubien** [comment]
Wanna give a try?

**Comment by urielfcampos** [comment]
I'd love to.

**Comment by lubien** [comment]
I made some comments on your commit @iagocavalcante

**Comment by lubien** [comment]
PDF is done. That leaves at least video and images. Edited description.

**Comment by lubien** [comment]
Closing as the most used formats where implemented.
